// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortEncode() {
  return window['go']['main']['App']['AbortEncode']();
}

export function GetTranslations(arg1) {
  return window['go']['main']['App']['GetTranslations'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectBDN() {
  return window['go']['main']['App']['SelectBDN']();
}

export function SetOutput() {
  return window['go']['main']['App']['SetOutput']();
}

export function StartEncode(arg1) {
  return window['go']['main']['App']['StartEncode'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
