// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {engine} from '../models';

export function AbortEncode():Promise<void>;

export function GetTranslations(arg1:number):Promise<Record<string, string>>;

export function LoadSettings():Promise<config.Settings>;

export function RevealOutput(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<boolean>;

export function SelectBDN():Promise<string>;

export function SetOutput():Promise<string>;

export function StartEncode(arg1:engine.EncodeConfig):Promise<boolean>;

export function Version():Promise<string>;
